[package]
name = "mdslw"
version = "0.5.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75", features = ["std", "backtrace"] }
clap = { version = "4.4.2", features = ["env", "derive"] }
ignore = "0.4"
include_dir = "0.7.3"
pulldown-cmark = { version = "0.9.3", default-features = false }
tempfile = "3.8.0"
